
export type ClientProfile = 'particular' | 'investor' | 'constructor' | 'company';
export type MaritalStatus = 'soltero' | 'casado' | 'divorciado' | 'viudo' | 'concubinato';

export interface Owner {
  id: string;
  name: string;
  dni: string;
  cuit: string;
  maritalStatus?: MaritalStatus;
}

export interface ContactData {
  email: string;
  phone: string;
  altPhone?: string;
  address: string;
  city: string;
  preferredContact: 'whatsapp' | 'call' | 'email';
}

// SELLER CLIENT (Vendedor)
export interface ClientRecord {
  id: string;
  userId?: string; // ID of the agent who owns this record
  createdByEmail?: string; // Email of the agent for display
  profileType: ClientProfile;
  owners: Owner[];
  contact: ContactData;
  notes?: string;
  tags: string[];
  createdAt: string;
  aiProfileSummary?: string;
}

// --- PROPERTY MODULE TYPES ---

export type PropertyType = 'departamento' | 'casa' | 'ph' | 'terreno' | 'local' | 'oficina';
export type PropertyStatus = 'disponible' | 'reservada' | 'vendida' | 'suspendida';
export type Currency = 'USD' | 'ARS';

// Detailed Zoning Data
export interface ZoningData {
  code: string;      // Código / Zonificación
  fot: string;       // Factor Ocupación Total
  fos: string;       // Factor Ocupación Suelo
  tps: string;       // Tipología / Premios / Otros
  maxHeight: string; // Altura Máxima
}

// Layout Configuration (for Room Calculation)
export interface LayoutConfig {
  kitchen: 'integrada' | 'separada' | 'kitchenette';
  living: 'integrado' | 'separado' | 'doble'; // integrado (comedor+living), separado (dos ambientes), doble (dos livings)
}

export interface PropertyRecord {
  id: string;
  userId?: string;
  createdByEmail?: string;
  clientId: string; // Foreign Key to ClientRecord
  customId: string; // e.g. PROP-001
  status: PropertyStatus;
  type: PropertyType;

  // Location
  address: {
    street: string;
    number: string;
    floor?: string;
    unit?: string;
    neighborhood: string;
    nomenclatura?: string;
    zoning: ZoningData; // Updated to Object
  };

  // Financials
  price: number;
  currency: Currency;
  creditEligible: boolean; // Apto Crédito

  // Surfaces
  surface: {
    covered: number;
    semiCovered: number;
    uncovered: number;
    total: number; // Auto-calculated
    lotFront?: number; // Only for House/Land
    lotDepth?: number; // Only for House/Land
  };

  // Physical (Hidden for Land)
  features: {
    layout: LayoutConfig; // New Layout Config
    rooms: number; // Auto-calculated (Ambientes)
    bedrooms: number;
    bathrooms: number;
    toilettes: number;
    age?: number;
    condition: 'a_estrenar' | 'muy_bueno' | 'bueno' | 'a_reciclar' | 'demolicion';
    orientation: 'norte' | 'sur' | 'este' | 'oeste';
    disposition: 'frente' | 'contrafrente' | 'interno' | 'lateral';
    parking: 'none' | 'covered' | 'uncovered';
    parkingType?: 'propia' | 'espacio';
  };

  // Amenities
  amenities: string[];
  hvac: 'gas' | 'radiadores' | 'losa' | 'central' | 'electrica'; // Updated Enum

  // Legal
  legal: {
    deedStatus: 'escritura' | 'boleto' | 'cesion';
    plans: 'aprobados' | 'no_tiene' | 'desactualizados'; // Removed "no coinciden"
    rules: {
      professionalUse: boolean;
      petsAllowed: boolean;
    };
  };

  // Expenses & Utilities
  expenses: {
    ordinary?: number;
    extraordinary?: number;
    extraordinaryEndDate?: string;
    taxesStatus: 'al_dia' | 'deuda';
    services: string[];
  };

  // Logistics
  logistics: {
    occupation: 'vacia' | 'alquilada' | 'habitada';
    contractExpiration?: string;
    keysLocation: 'oficina' | 'dueño' | 'inquilino'; // Updated Enum
    signage: boolean; // Cartel
  };

  // Files Storage (Simulated)
  files: {
    photos: string[];
    documents: string[]; // Legal
    debts: string[]; // Bills/Debt status
  };

  createdAt: string;
  aiAnalysis?: string; // Analysis generated by Gemini
}

// --- MARKETING MODULE TYPES (NEW) ---

export interface MarketingMetrics {
  publications: number; // Cantidad de veces publicado
  impressions: number;
  clicks: number;
  inquiries: number; // Consultas
}

export interface MarketingLog {
  id: string;
  propertyId: string;
  date: string; // Fecha de carga
  period: '14_days';

  marketplace: MarketingMetrics;
  social: MarketingMetrics; // FB Page + IG Organic
  ads: MarketingMetrics; // Meta Ads (Paid)
}

// --- BUYER MODULE TYPES ---

export type SearchStatus = 'activo' | 'pausa' | 'concretado' | 'caido';
export type PaymentMethod = 'contado' | 'credito' | 'financiacion';

// 1. BUYER CLIENT (The Person)
export interface BuyerClientRecord {
  id: string;
  userId?: string;
  createdByEmail?: string;
  name: string;
  dni: string;
  phone: string;
  email: string;
  address?: string;
  type: 'consumidor_final' | 'inversor' | 'corporativo';
  notes?: string;
  createdAt: string;
}

// 2. BUYER SEARCH (The NURC Profile)
export interface BuyerSearchRecord {
  id: string;
  userId?: string;
  buyerClientId: string; // Foreign Key to BuyerClientRecord
  agentName: string;
  status: SearchStatus;

  // NURC Profile
  searchProfile: {
    // Need
    propertyTypes: PropertyType[]; // Multi-select
    zones: string[]; // Array of strings (neighborhoods)
    minRequirements: {
      bedrooms: number;
      bathrooms: number;
      totalSurface: number;
    };
    exclusions: {
      mustHaveGarage: boolean;
      mustHaveOutdoor: boolean; // Balcon/Patio
      mortgageRequired: boolean; // Apto Crédito
      acceptsOffPlan: boolean; // Pozo
    };

    // Urgency
    timeline: 'inmediato' | '30_60_dias' | '6_meses' | 'sin_apuro';
    trigger: 'vencimiento_alquiler' | 'cambio_familia' | 'inversion' | 'otro';
    availability: string; // Textarea

    // Resources
    budget: {
      max: number;
      currency: Currency;
    };
    paymentMethod: PaymentMethod;
    salesCondition: {
      needsToSell: boolean;
      isPropertyCaptured: boolean;
      linkedPropertyId?: string; // Link to PropertyRecord.id
    };
    acceptsSwap: boolean; // Permuta

    // Capacity
    decisionMakers: string; // Textarea

    // Qualitative Notes (New for Interview Guide)
    nurcNotes: {
      n: string;
      u: string;
      r: string;
      c: string;
      updates?: string; // NEW: Stores post-visit corrections
    };
  };

  createdAt: string;
}

// --- VISIT & AGENDA MODULE TYPES ---

export type VisitStatus = 'pendiente' | 'realizada' | 'cancelada';
export type VisitDuration = '15' | '30' | '60';
// UPDATED LEAD SOURCE TO MATCH MARKETING CHANNELS
export type LeadSource = 'marketplace' | 'social' | 'ads' | 'cartel' | 'referido' | 'otro';

export interface VisitFeedback {
  rating: number; // 1-5 Stars
  pricePerception: 'barato' | 'justo' | 'caro';
  interestLevel: 'caliente' | 'tibio' | 'frio';
  positivePoints: string;
  objections: string;
  nurcMatch: boolean; // Did it match expectations?
  searchCriteriaUpdate?: string; // If no match, how should we update the search?
}

export interface VisitNextSteps {
  action: 'ofertar' | 'segunda_visita' | 'buscar_similares' | 'descartar';
  followUpDate?: string;
}

export interface VisitRecord {
  id: string;
  userId?: string;
  propertyId: string; // Link to Property
  buyerClientId: string; // Link to Buyer Client
  agentName: string;

  // Origin
  source?: LeadSource; // Where did the lead come from?

  // Schedule
  date: string; // ISO String (YYYY-MM-DD)
  time: string; // HH:mm
  duration: VisitDuration;
  meetingPoint: 'propiedad' | 'oficina' | 'otro';
  securityCheck: boolean; // Occupant notified?

  // New Manual Fields
  manualPropertyAddress?: string;
  comments?: string;

  // Execution
  status: VisitStatus;
  signedConfirmation: boolean; // Hoja de visita firmada
  signedConfirmationFile?: string; // URL/Path to the signed document

  // Post-Visit
  feedback?: VisitFeedback;
  nextSteps?: VisitNextSteps;

  createdAt: string;
}

// --- TRACKING & RELATIONSHIPS TYPES (NEW) ---

export type ActivityType = 'act_verde' | 'reunion_verde' | 'pre_listing' | 'pre_buying' | 'acm' | 'captacion' | 'visita' | 'reserva' | 'cierre' | 'referido';

export interface GlobalContact {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  source: 'seller_db' | 'buyer_db' | 'relationship_db';
  originalId?: string; // ID in the original table
  createdAt: string;
}

export interface ActivityRecord {
  id: string;
  userId?: string;
  date: string; // ISO Date YYYY-MM-DD
  type: ActivityType;
  contactId?: string;
  contactName: string;
  notes?: string;
  referenceId?: string;
  systemGenerated?: boolean;
  createdAt: string;
}

// --- CLOSING TYPES (NEW) ---

export interface ClosingRecord {
  id: string;
  userId?: string;
  propertyId?: string;
  manualProperty?: string;
  buyerClientId?: string;
  manualBuyer?: string;
  date: string; // YYYY-MM-DD
  agentName: string;
  salePrice: number;
  currency: Currency;
  commissionPercent: number;
  sides: 1 | 2;
  isShared: boolean;
  totalBilling: number;
  agentHonorarium: number;
  createdAt: string;
  operationType: 'venta' | 'alquiler';
  subSplitPercent: number;
  exchangeRateSnapshot?: number;
  referralSidesApplied?: 1 | 2; // NEW: How many sides the referral % applies to (default: same as 'sides')
}


export interface KPIDashboardRow {
  user_id: string;
  anio: number;
  // Financials
  facturacion_total: number;
  transacciones_cerradas: number; // Puntas
  transacciones_operaciones: number; // NEW: Operaciones para el promedio
  volumen_total: number;
  ticket_promedio: number; // Por Operación
  honorarios_reales: number;
  // Activities
  total_pl: number;
  total_pb: number;
  total_captaciones: number;
  total_reuniones_verdes: number;
  total_gestion: number; // Calculated in view
  // Ratios
  efectividad_cierre: number;
  efectividad_captacion: number;
  honorarios_promedio: number; // NEW: NCI promedio por punta
  productividad_actividad: number; // NEW: Honorarios / Total Actividades
  // Objectives
  annual_billing: number;
  monthly_need: number;
}

